<template>
    <div class="d-flex inner__content profile-content messanger__wrapper big"><div class="d-flex messanger"><div class="d-flex flex-column messanger-left"><div class="message active"><img src="https://www.thefashionisto.com/wp-content/uploads/2019/07/Male-Model-Businessman-Suit.jpg" alt=""> <div class="message__content"><p class="name">Kanoy82</p> <div class="d-flex mb-2 w-100 justify-content-between"><span class="rang">rookie (021)</span> <span class="time">43 min ago.</span></div> <p class="text">Hi lucy. 3D computer graphics (in contrast to 2D computer
        graphics) are graphics that utilize a three-dimensional
        representation of geometric data that is stored in the fut...</p></div></div> <div class="message"><img src="https://www.themodestman.com/wp-content/uploads/2018/01/fp1-mobile-4.jpg" alt=""> <div class="message__content"><p class="name">3Dpresident</p> <div class="d-flex mb-2 w-100 justify-content-between"><span class="rang">master (5321)</span> <span class="time">30 min ago.</span></div> <p class="text">Hi lucy. 3D computer graphics (in contrast to 2D computer
        graphics) are graphics that utilize a three-dimensional
        representation of geometric data that is stored in the fut...</p></div></div> <div class="message"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6qV59E-AQoig2m7MwDJRM9j8oWE4tb2DdAA&amp;usqp=CAU" alt=""> <div class="message__content"><p class="name">Mark 1</p> <div class="d-flex mb-2 w-100 justify-content-between"><span class="rang">user (321)</span> <span class="time">1 hr ago.</span></div> <p class="text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. eos veniamNecessitatibus, culpa ea inventore illum eos veniamNecessitatibus, culpa ea inventore illum eos veniam...</p></div></div> <div class="message"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdnrnWmvzFENEYLnpY3MLrmu-lYEuXwBAY2g&amp;usqp=CAU" alt=""> <div class="message__content"><p class="name">Gayana_arm</p> <div class="d-flex mb-2 w-100 justify-content-between"><span class="rang">admin (211)</span> <span class="time">15 hr ago.</span></div> <p class="text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus, necessitatibus! Dignissimos, sed laborum maiores adipisci at vel odio dolore, iusto ex tempora obcaecati est nihil omnis quo deserunt soluta repudiandae voluptates sapiente. Eos cum repellat reprehenderit, sit laboriosam autem officiis vitae quia aliquid eum quos labore consequatur expedita. Minus, qui...</p></div></div> <div class="message"><img src="https://www.thefashionisto.com/wp-content/uploads/2019/07/Male-Model-Businessman-Suit.jpg" alt=""> <div class="message__content"><p class="name">Kanoy82</p> <div class="d-flex mb-2 w-100 justify-content-between"><span class="rang">rookie (021)</span> <span class="time">43 min ago.</span></div> <p class="text">Hi lucy. 3D computer graphics (in contrast to 2D computer
        graphics) are graphics that utilize a three-dimensional
        representation of geometric data that is stored in the fut...</p></div></div> <div class="message"><img src="https://www.themodestman.com/wp-content/uploads/2018/01/fp1-mobile-4.jpg" alt=""> <div class="message__content"><p class="name">3Dpresident</p> <div class="d-flex mb-2 w-100 justify-content-between"><span class="rang">master (5321)</span> <span class="time">30 min ago.</span></div> <p class="text">Hi lucy. 3D computer graphics (in contrast to 2D computer
        graphics) are graphics that utilize a three-dimensional
        representation of geometric data that is stored in the fut...</p></div></div> <div class="message"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6qV59E-AQoig2m7MwDJRM9j8oWE4tb2DdAA&amp;usqp=CAU" alt=""> <div class="message__content"><p class="name">Mark 1</p> <div class="d-flex mb-2 w-100 justify-content-between"><span class="rang">user (321)</span> <span class="time">1 hr ago.</span></div> <p class="text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. eos veniamNecessitatibus, culpa ea inventore illum eos veniamNecessitatibus, culpa ea inventore illum eos veniam...</p></div></div> <div class="message"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdnrnWmvzFENEYLnpY3MLrmu-lYEuXwBAY2g&amp;usqp=CAU" alt=""> <div class="message__content"><p class="name">Gayana_arm</p> <div class="d-flex mb-2 w-100 justify-content-between"><span class="rang">admin (211)</span> <span class="time">15 hr ago.</span></div> <p class="text">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusamus, necessitatibus! Dignissimos, sed laborum maiores adipisci at vel odio dolore, iusto ex tempora obcaecati est nihil omnis quo deserunt soluta repudiandae voluptates sapiente. Eos cum repellat reprehenderit, sit laboriosam autem officiis vitae quia aliquid eum quos labore consequatur expedita. Minus, qui...</p></div></div></div> <div class="d-flex flex-column messanger-right"><div class="content"><div class="message guest"><img src="https://www.thefashionisto.com/wp-content/uploads/2019/07/Male-Model-Businessman-Suit.jpg" alt=""> <div class="message__content"><p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam consequuntur accusantium a beatae eum reiciendis!
    </p></div></div> <div class="message main"><img src="img/rookie.jpg" alt=""> <div class="message__content"><p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim, facere debitis? Commodi blanditiis quo in voluptatem iusto, dolorum, numquam sed vero eius ducimus consequuntur deserunt rem animi. Culpa, dolorem quaerat!
    </p></div></div> <p class="today">today</p> <div class="message guest"><img src="https://www.thefashionisto.com/wp-content/uploads/2019/07/Male-Model-Businessman-Suit.jpg" alt=""> <div class="message__content"><p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam consequuntur accusantium a beatae eum reiciendis!
    </p></div></div> <div class="message main"><img src="img/rookie.jpg" alt=""> <div class="message__content"><p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim, facere debitis? Commodi blanditiis quo in voluptatem iusto, dolorum, numquam sed vero eius ducimus consequuntur deserunt rem animi. Culpa, dolorem quaerat!
    </p></div></div> <div class="message guest"><img src="https://www.thefashionisto.com/wp-content/uploads/2019/07/Male-Model-Businessman-Suit.jpg" alt=""> <div class="message__content"><p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam consequuntur accusantium a beatae eum reiciendis!
    </p></div></div> <div class="message main"><img src="img/rookie.jpg" alt=""> <div class="message__content"><p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim, facere debitis? Commodi blanditiis quo in voluptatem iusto, dolorum, numquam sed vero eius ducimus consequuntur deserunt rem animi. Culpa, dolorem quaerat!
    </p></div></div></div> <form action="" class="d-flex"><textarea type="text" class="form-control"></textarea> <button class="btn btn-red">send</button></form></div></div></div>
</template>

<script>
    export default {
        name: "Messages"
    }
</script>

<style scoped>

</style>
